### PR TITLE
Coveralls and ci-helpers

### PR DESCRIPTION
**Pull request by hamogu**

### CODE REVIEW

**Comment by hamogu** [comment]
@bsipocz : If you have a few minutes, could you have a look at these failures? I know that it's not your package but either I've done something wrong with ci-helpers or I'm just stupid...

(No hurry - I have a working test setup right now and I can update to ci-helpers at any point in the future.)

**Comment by bsipocz** [comment]
@hamogu - Thanks for the reports, half of the fails is I think issues with your setup, but the other half may be some bug in ``ci-helpers``. I'll try to come back to it later today or tomorrow.

**Comment by hamogu** [comment]
@bsipocz : Can you have a look at this build: https://travis-ci.org/Chandra-MARX/marxs/jobs/131796848

It seems that the tests are never run, because something went wrong (with an exit status of 0,so that is looks green) in the ci-helpers script.

**Comment by bsipocz** [comment]
@hamogu - yep, that's normal. If there is no prerelease numpy available it quits during install and sets the build green (otherwise that fallback numpy version is stable, and there should be another build for that already).

**Pull request merged**
