### PR TITLE
Update astropy-helpers to v2.0.2

### PR DESCRIPTION
**Pull request by bsipocz**
This is an automated update of the astropy-helpers submodule to v2.0.2. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*

### CODE REVIEW

**Comment by bsipocz** [comment]
(Sorry for the many commits, editing on github is not amend/squash friendly, but at least quick...)

**Comment by hamogu** [comment]
Don't worry about the number of commits.  Thank you so much for doing this and even fixing two unrelated mistakes in the process!

**Comment by hamogu** [comment]
I just looked into upgrading the entire package again, but there still is no good replacement for mayavi. While there is more than way to get a mayavi build for python 3 e.g. on some channel on conda, none of them is really satisfactory, e.g. one is not available for Mac, some depend on unreleased bleeding edge versions of other packages etc. Until that improves, I myself with use this package on python 2.7, so I can't drop 2.7 support.

**Comment by bsipocz** [comment]
Oh, sure enough that case seems to be sensible. The only thing to look out then, is to note that ``marxs`` in the docs, that astropy LTS (2.0.x) is required. And also update the CI tests once 3.0 is out to use LTS rather than stable. (Or you can add numbered version requirement, too). 

Anyway, you'll notice this as the build will stop passing at that point.

**Pull request merged**
